# Generated by Django 4.1.1 on 2022-09-27 18:00

from django.db import migrations, models
import src.bookshelf.utils


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_read',
            field=models.BooleanField(blank=True, null=True, verbose_name='прочитано'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=src.bookshelf.utils.user_directory_path, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
    ]
