# Generated by Django 4.1.1 on 2022-09-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-date_created', 'title'), 'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
    ]
