# Generated by Django 4.1.1 on 2022-09-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-date_updated', 'title'), 'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
    ]
