# Generated by Django 4.1.1 on 2022-09-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_old_system',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
